### PR TITLE
Move to WKWebView

### PR DESCRIPTION
**Pull request by stefanalund**
Now reloads and navigation does not interfere with WebRTC support (injection), making the app much faster and more reliable. 

Requires iOS 9.0.

### CODE REVIEW

**Comment by stefanalund** [comment]
Closes https://github.com/EricssonResearch/bowser/issues/1.

**Comment by truestep** [comment]
Cool. Is this change in appstore already?

**Comment by stefanalund** [comment]
Nope, not yet. We want to test it more and merge it before posting a new version. Let us know if it works for you! Also, we are going to make a new release of OpenWebRTC that, among other things, fixes Bowser crashes on 32-bit devices.

**Comment by stefanalund** [comment]
@stefhak had any chance to look at this?

**Comment by bamboolsu** [comment]
Maybe we can fix these issues of #359, #504 and  #510 when we release new version.

**Comment by stefanalund** [comment]
@bamboolsu yes, but I would not like to wait too long before publishing a new version of Bowser. I would rather make incremental updates once we fix different issues. Have you verified that this version of Bowser works as well/bad as the previous one (without WKWebView)?

**Comment by stefanalund** [comment]
@superdump @stefhak OK to land this?

**Comment by stefhak** [comment]
I have not the competence to test, but from my perspective, given what I can judge, we should merge.
My only question would be if the version of owr you build on has the string '"profileLevelId": "42e01f",' in webrtc.js; if so I'd remove it as it negotiates h264 with FF, but things seem to be very unstable.

**Comment by superdump** [comment]
:+1: It's nice that so much code can be removed. As long as it's tested against OWR, Chrome and Firefox, go ahead and merge it.

**Comment by stefanalund** [comment]
The remaining question for me is whether we should make a new pod release first. I have been testing with my own build of a more recent OpenWebRTC.

**Pull request closed without merging**
